STATE_INIT = 0
STATE_USER_SELECT = 10
STATE_USER0_JOIN = 11
STATE_USER1_JOIN = 12
STATE_USER2_JOIN = 13
STATE_DIFFICULTY_SELECTED = 20
STATE_ANSWER_SELECTED = 30
STATE_JASMINE_SELECTED = 40

GAME_EASY = 0
GAME_HARD = 1

DRINK_MELON = 0
DRINK_ORANGE = 1
DRINK_OOLONG = 2
DRINK_JASMINE = 3

DUMMY_USER_ID0 = 'Uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
DUMMY_USER_ID1 = 'Uyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'